# Configuração do Supabase para CRM-MARKETING
# A local development stack file

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
enable_manual_linking = false

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[functions]
enabled = true
port = 54327

[analytics]
enabled = false

# Remote project configuration
[project]
# Supabase project reference ID
project_id = "marajvabdwkpgopytvhh" 